# Generated by Django 5.1.4 on 2024-12-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_delivery_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='custodian',
            name='custodian_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_address',
            field=models.CharField(max_length=255),
        ),
    ]
